# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:21:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Declination(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class GridVariation(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class Inclination(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class TotalIntensity(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class MagneticFieldGetResponse(BaseModel):
    declination: Optional[Declination] = Field(
        None,
        description='The angle in the horizontal plane between magnetic north and true north. Declination is positive when magnetic north is east of true north.\n',
    )
    grid_variation: Optional[GridVariation] = Field(
        None,
        description='Referenced to grid north, referenced to 0 deg meridian of a polar stereographic projection.  Only defined for latitudes greater than 55 degrees and less than -55 degrees (arctic and antarctic).\n',
    )
    inclination: Optional[Inclination] = Field(
        None,
        description="Also known as 'dip', is the angle made between the horizontal plane and the magnetic field vector at some position. Positive inclination corresponds to a downward pointing. \n",
    )
    total_intensity: Optional[TotalIntensity] = Field(
        None, description='Total magnetic field intensity in nano Teslas.\n'
    )
